import {StyleSheet} from 'react-native';

const AppColors = {
  PRIMARY_COLOR: '#e66125',
  COLOR_WHITE: '#ffffff',
  BG_COLOR: '#621FF7',
  ORANGE: 'orange',
  GREEN: 'green',
  COLOR_NOTIF_BG: '#fbaf5d',
  COLOR_GREY: '#666666',
};
export {AppColors};

const AppIcons = {
  ALERT_ICON: require('../../assets/alert.png'),
  DUMMY_ICON: 'https://jawa.linksdev.co.uk/images/Noimage.jpg',

};
export {AppIcons};

const AppDimens = StyleSheet.create({
  halfOne: 0.5,
  one: 1,
  two: 2,
  twoPFive: 2.5,
  twoPseven: 2.7,
  three: 3,
  threePthree: 3.3,
  four: 4,
  fourPFive: 4.5,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
  ten: 10,
  twelve: 12,
  thirteen: 13,
  forteen: 14,
  fifteen: 15,
  sixteen: 16,
  seventeen: 17,
  eighteen: 18,
  twenty: 20,
  twentyTwo: 22,
  twentyFive: 25,
  thirty: 30,
  thirtyTwo: 32,
  thirtyFive: 35,
  forty: 40,
  fortyFive: 45,
  fifty: 50,
  fiftyFive: 55,
  sixty: 60,
  sixtyFive: 65,
  seventy: 70,
  seventyFive: 75,
  eighty: 80,
  eightyTwo: 82,
  eightyFive: 85,
  ninty: 90,
  nintyFive: 95,
  hundred: 100,
  oneTen: 110,
  oneTwenty: 120,
  oneTwentyFive: 125,
  oneThirty: 130,
  oneForty: 140,
  oneFortyEight: 148,
  oneFifty: 150,
  oneEighty: 180,
  oneNighttyEight: 198,
  twoHundred: 200,
});
export {AppDimens};

const AppTexts = {
  centerText: 'center',
  leftText: 'flex-start',
  left: 'left',
  rightText: 'flex-end',
  textAtTop: 'top',
  absolute: 'absolute',
  spaceBetween: 'space-between',
  NO_WRAP: 'nowrap',
  bottomText: 'bottom',
  boldText: 'bold',
  justify: 'justify',
  underline: 'underline',
  column: 'column',
  row: 'row',
  flexStart: 'flex-start',
  flexEnd: 'flex-end',
  resizeContain: 'contain',
  resizeCover: 'cover',
  stretch: 'stretch',

  fontFamily: 'museo-sans-300',
};
export {AppTexts};
